name: First Workflow
on: 
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step of Job1
        run: |
          echo "first step of Job1"
          echo "first step of Job2"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step of Job2
        run: echo "first step of Job2"
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: first step of Job3
        uses : actions/checkout@v6
      - name: second step of Job3  
        run: ls; pwd
